// Code generated by Slice Machine. DO NOT EDIT.

import Banner from "./Banner/index.svelte";
import HeroSection from "./HeroSection/index.svelte";
import Projects from "./Projects/index.svelte";

export const components = {
  banner: Banner,
  hero_section: HeroSection,
  projects: Projects,
};
